WebApplication1/Controllers/GioHangController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.ViewModel;
using X.PagedList.Extensions;

namespace WebApplication1.Controllers
{
    public class GioHangController : Controller
    {
        AppDbContext _context;
        public GioHangController(AppDbContext dbContext)
        {
            _context = dbContext;
        }
        public IActionResult Index(int page = 1, int pageSize = 3)
        {
            var idGioHang = Guid.Parse(HttpContext.Session.GetString("IdGioHang"));
            var gioHang = _context.ChiTietGioHangs.Where(c => c.GioHangId == idGioHang).Join(_context.SanPhams, c => c.SanPhamId, s => s.Id, (c, s) => new GioHangViewModel
            {
                Id = s.Id,
                TenSanPham = s.Name,
                Gia = s.Price,
                SoLuong = c.SoLuong,
                TongTien = c.SoLuong * s.Price,
            }).ToPagedList(page, pageSize);
            return View(gioHang);
        }
        public IActionResult Remove(Guid id)
        {
            var sanPham = _context.SanPhams.Find(id);
            if (sanPham != null)
            {
                var idGioHang = Guid.Parse(HttpContext.Session.GetString("IdGioHang"));
                var chiTietGioHang = _context.ChiTietGioHangs.FirstOrDefault(c => c.SanPhamId == id && c.GioHangId == idGioHang);
                if (chiTietGioHang == null)
                    return Content("Khong co san pham nay");
                else
                {
                    _context.ChiTietGioHangs.Remove(chiTietGioHang);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            else
                return Content("khong co san pham nay");
        }
        public IActionResult ThanhToan()
        {
            List<ChiTietGioHang> chiTietGioHangs = _context.ChiTietGioHangs.Include(c => c.SanPham).Where(c => c.GioHangId == Guid.Parse(HttpContext.Session.GetString("IdGioHang"))).ToList();
            if (chiTietGioHangs == null)
                return Content("Gio hang trong");
            else
            {
                DateTime thisTime = DateTime.Now;
                var hoaDon = new HoaDon()
                {
                    UserId = Guid.Parse(HttpContext.Session.GetString("UserId")),
                    NgayTao= thisTime,
                    ThanhTien = 0,
                };
                _context.HoaDons.Add(hoaDon);
                _context.SaveChanges();
                decimal tongTien = 0;
                List<ChiTietHoaDonViewModel> chiTietHoaDonViewModels = new List<ChiTietHoaDonViewModel>();
                var currentHoaDon = _context.HoaDons.FirstOrDefault(c => c.UserId == hoaDon.UserId && c.NgayTao == thisTime);
                foreach (var item in chiTietGioHangs)
                {
                    var sanPham= item.SanPham;
                    if (sanPham.SoLuong >= item.SoLuong)
                        sanPham.SoLuong -= item.SoLuong;
                    else
                        return Content($"{sanPham.Name} Không đủ tồn kho");
                    var chiTietHoaDon = new ChiTietHoaDon()
                    {
                        SanPhamId = item.SanPhamId,
                        SoLuong = item.SoLuong,
                        ThanhTien = item.SoLuong * item.SanPham.Price,
                        HoaDonId = currentHoaDon.Id
                    };
                    tongTien += chiTietHoaDon.ThanhTien;
                    _context.ChiTietHoaDons.Add(chiTietHoaDon);
                    var chiTietHoaDonViewModel = new ChiTietHoaDonViewModel()
                    {
                        TenSanPham=item.SanPham.Name,
                        SoLuong=item.SoLuong,
                        ThanhTien=chiTietHoaDon.ThanhTien
                    };
                    chiTietHoaDonViewModels.Add(chiTietHoaDonViewModel);
                    currentHoaDon.ThanhTien = tongTien;
                }
                _context.ChiTietGioHangs.RemoveRange(chiTietGioHangs);
                _context.SaveChanges();
                ViewBag.ThanhTien = currentHoaDon.ThanhTien;
                ViewBag.NgayTao=currentHoaDon.NgayTao;
                return View(chiTietHoaDonViewModels);
            }
        }
    }
}

WebApplication1/Controllers/HoaDonController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    public class HoaDonController : Controller
    {
        AppDbContext _context;
        public HoaDonController(AppDbContext dbContext)
        {
            _context = dbContext;
        }
        public IActionResult Index()
        {
            var hoaDons= _context.HoaDons.Where(c=>c.UserId==Guid.Parse(HttpContext.Session.GetString("UserId"))).ToList();
            return View(hoaDons);
        }
        public ActionResult Details(Guid id)
        {
            var hoaDon=_context.HoaDons.Find(id);
            if (hoaDon == null)
                return Content("Không có hóa đơn");
            else
            {
                List<ChiTietHoaDonViewModel> chiTietHoaDonVMs = _context.ChiTietHoaDons.Where(c => c.HoaDonId == id).Join(_context.SanPhams,h=>h.SanPhamId,s=>s.Id,(h,s)=> new ChiTietHoaDonViewModel
                {
                    TenSanPham=s.Name,
                    SoLuong=h.SoLuong,
                    ThanhTien=h.ThanhTien,
                }).ToList();
                ViewBag.NgayTao = hoaDon.NgayTao;
                ViewBag.ThanhTien = hoaDon.ThanhTien;
                return View(chiTietHoaDonVMs);
            }

        }
    }
}

WebApplication1/Controllers/SanPhamController.cs
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;
using WebApplication1.Models;
using X.PagedList.Extensions;

namespace WebApplication1.Controllers
{
    public class SanPhamController : Controller
    {
        AppDbContext _context;
        public SanPhamController(AppDbContext db)
        {
            _context = db;
        }
        [HttpGet]
        public IActionResult Index(int page = 1, int pageSize = 3)
        {
            var name = HttpContext.Session.GetString("Name");
            if (string.IsNullOrEmpty(name))
            {
                return Content("Chưa đang nhập");
            }
            else
            {
                var sanPhams = _context.SanPhams.ToPagedList(page, pageSize);
                return View(sanPhams);
            }
        }
        [HttpPost]
        public ActionResult Index(string key, int page = 1, int pageSize = 3)
        {

            if (string.IsNullOrEmpty(key))
            {
                return View(_context.SanPhams.ToPagedList(page, pageSize));
            }
            else
            {
                key = key.ToLower().Trim();
                var result = _context.SanPhams.Where(c => c.Name.ToLower().Contains(key)).ToPagedList(page, pageSize);
                if (result == null)
                {
                    ViewBag.Message = "Không có sản phẩm nào";
                    return View();
                }
                else
                {
                    return View(result);
                }
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(SanPham sanPham, IFormFile Img)
        {
            try
            {
                if (Img != null && Img.Length > 0)
                {
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", Img.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        Img.CopyTo(stream);
                    }
                    sanPham.ImgUrl = Img.FileName;
                }
                _context.SanPhams.Add(sanPham);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
        }
        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var sanPham = _context.SanPhams.Find(id);
            return View(sanPham);
        }
        [HttpPost]
        public ActionResult Edit(SanPham sanPham)
        {
            _context.SanPhams.Update(sanPham);
            _context.SaveChanges(true);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Buy(Guid idSanPham, int soLuong)
        {
            var name = HttpContext.Session.GetString("Name");
            var idGioHang = Guid.Parse(HttpContext.Session.GetString("IdGioHang"));
            if (string.IsNullOrEmpty(name))
            {
                return Content("Chưa đang nhập");
            }
            else
            {
                var check = _context.ChiTietGioHangs.FirstOrDefault(c => c.SanPhamId == idSanPham && c.GioHangId == idGioHang);
                if (check == null)
                {
                    var chiTietGioHang = new ChiTietGioHang()
                    {
                        SanPhamId = idSanPham,
                        GioHangId = Guid.Parse(HttpContext.Session.GetString("IdGioHang")),
                        SoLuong = soLuong
                    };
                    _context.ChiTietGioHangs.Add(chiTietGioHang);
                }
                else
                {
                    check.SoLuong += 1;
                }
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

WebApplication1/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.ViewModel;

namespace WebApplication1.Controllers
{
    public class UserController : Controller
    {
        AppDbContext _context;
        public UserController(AppDbContext db)
        {
            _context = db;
        }
        // GET: UserController
        public ActionResult Index(int currentPage, int pageChange)
        {
            var userName = HttpContext.Session.GetString("UserName");
            if (userName == "Admin")
            {
                var users = _context.Users.ToList();
                var lastPage = (int)Math.Ceiling((float)users.Count / (float)5);
                if (currentPage + pageChange > lastPage || currentPage == 0)
                    currentPage = 1;
                else if (currentPage + pageChange < 1)
                    currentPage = (int)lastPage;
                else
                    currentPage += pageChange;
                ViewBag.LastPage = lastPage;
                ViewBag.CurrentPage = currentPage;
                var usersPage = users.OrderBy(c => c.Name).Skip((currentPage - 1) * 5).Take(5).ToList();
                return View(usersPage);
            }
            else
            {
                return Content("Không đủ quyền");
            }
        }

        // GET: UserController/Details/5
        public ActionResult Details(Guid id)
        {
            var user = _context.Users.FirstOrDefault(u => u.Id == id);
            return View(user);
        }

        // GET: UserController/Create
        public ActionResult Regiter()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Regiter(User user)
        {
            try
            {
                _context.Users.Add(user);
                var giohang = new GioHang()
                {
                    UserId = user.Id,
                };
                _context.Add(giohang);
                _context.SaveChanges();
                return RedirectToAction("Login");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User Update)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel loginViewModel)
        {
            var user = _context.Users.Include(u => u.GioHang).FirstOrDefault(c => c.Username == loginViewModel.Username && c.Password == loginViewModel.Password);
            if (user != null)
            {
                HttpContext.Session.SetString("Name", user.Name.ToString());
                HttpContext.Session.SetString("UserName", user.Username.ToString());
                HttpContext.Session.SetString("UserId", user.Id.ToString());
                HttpContext.Session.SetString("IdGioHang", user.GioHang.Id.ToString());
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Error = "Invalid username or password";
                return View(loginViewModel);
            }
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("Name");
            HttpContext.Session.Remove("UserName");
            HttpContext.Session.Remove("UserId");
            HttpContext.Session.Remove("IdGioHang");
            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SanPham" asp-action="Index">SanPham</a>
                        </li>
                    </ul>
                     <ul class="navbar-nav navbar-right">
                        @{
                            var name = HttpContextAccessor.HttpContext.Session.GetString("Name");
                            if (string.IsNullOrEmpty(name))
                            {
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-controller="User" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-warning" asp-controller="User" asp-action="Regiter">Register</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <span class="nav-link navbar-text">Hello, @name</span>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-danger" asp-controller="GioHang" asp-action="Index">Giỏ hàng</a>
                                </li>
                                <p>|</p>
                                <li class="nav-item">
                                    <a class="btn btn-danger" asp-controller="HoaDon" asp-action="Index">Hóa đơn</a>
                                </li>
                                <p>|</p>
                                <li class="nav-item">
                                    <a class="btn btn-danger" asp-controller="User" asp-action="Logout">Logout</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>